### PR TITLE
Bug/improve add close button

### PR DESCRIPTION
**Pull request by kodcuserkan**
this done

### CODE REVIEW

**Comment by feruzm** [comment]
@kodcuserkan  On hover, icon background/opacity decreasing, let's remove that hover color change?
image

**Comment by feruzm** [comment]
also there is this warning/error on terminal.
image

**Comment by kodcuserkan** [comment]
Both of them fixed

**Comment by feruzm** [comment]
@kodcuserkan in proposals page, check how we do it and it is perfectly centered.
image

But in this modal, it looks bit off, also maybe icon being set twice for some reason?
image

**Comment by kodcuserkan** [comment]
centered now
Screen Shot 2021-05-16 at 23 53 19

**Review by feruzm — APPROVED** [review]

**Pull request merged**
