### PR TITLE
Fix css for notification list on hover

### PR DESCRIPTION
**Pull request by tipyy**

### CODE REVIEW

**Comment by tipyy** [comment]
There is a little CSS bug on the notification list on mouse hover.


https://user-images.githubusercontent.com/2386470/130354772-5bb41903-d939-4932-b12f-3c807eb95070.mov


This pull request fix this issue.

**Review by feruzm — APPROVED** [review]
lgtm, thank you!

**Comment by feruzm** [comment]
@tipyy next time please do PR to development, it goes to alpha.ecency.com and we bundle release together and do some tests first as oppose to pushing fixes directly to production

**Comment by tipyy** [comment]
My bad, I'll know for the next PR.

**Pull request merged**
