### PR TITLE
Store post and comment vote percentages

### PR DESCRIPTION
**Pull request by MTSaeed**
**What does this PR?**

It will store the last vote percentage of post and comment in local storage.
If there is previously stored value in local storage , it will get the value from local storage and display the previous voted value.
If there is no value in local storage means user open the voting slider first time, it will display the default value in the slider.

**Steps to reproduce**

1. Open the voting slider of any post and vote to that post or just move the slider to change the value of slider. it will store the updated value of slider in local storage.
2. When you open the slider of any post next time, it will show and  set the previous stored value.
3. Same is the case with comment-voting-slider.But post-voting-slider value and comment-voting-slider value stored separately and  independent to each other.
4. Stored the value of slider in both **Up** and **Down** case.

**Issue number** 

fixes #[1048](https://github.com/ecency/ecency-vision/issues/1048)

**Screenshots/Video**

https://user-images.githubusercontent.com/106739598/205293384-87226905-d016-405f-94e4-9034421292a9.mp4

### CODE REVIEW

**Comment by feruzm** [comment]
@MTSaeed Do we still show voted value? If content already has been voted, slider should show that value not localstorage value.

**Comment by MTSaeed** [comment]
@feruzm @dkildar The code has been updated please review. 

Currently we are saving the voted value in localstorage and showing that on slider next time if the user has voted on one post or comment. If the user just changes the value on slider and has not voted the value is not saved and the voted one will be displayed next time.

**Comment by feruzm** [comment]
@MTSaeed I am talking about, content is voted by user with 40% and later another content was voted with 50%. If person opens first content vote again, do we show 40% or 50% ?

**Comment by MTSaeed** [comment]
> @MTSaeed I am talking about, content is voted by user with 40% and later another content was voted with 50%. If person opens first content vote again, do we show 40% or 50% ?

It would say 40% as that post has been voted 40%. 

https://user-images.githubusercontent.com/106739598/206150706-e7d6510d-77cf-480e-8768-d615a5c50428.mp4

If a post is voted it would show the voted value instead of LS.

**Review by feruzm — APPROVED** [review]
lgtm, will require more testing on production alpha https://alpha.ecency.com

**Pull request merged**
