### PR TITLE
sort engine tokens

### PR DESCRIPTION
**Pull request by Adesojisouljay**

### CODE REVIEW

**Review by feruzm — CHANGES_REQUESTED** [review]
@Adesojisouljay Redundant wording is not necessary, just show icon or Sort as initial label and from other options remove Sort by

Ascending
Descending
Balance 
....
(Most amount related should do descending showing more balance on top)

Also consider adding sort by Value option to show most valued on top.



image

**Comment by Adesojisouljay** [comment]
Noted, I will make corrections and pull.
Thanks.

**Comment by Adesojisouljay** [comment]
### What does this PR ?

Basically, this PR sorts hive engine tokens in ascending and descending order, also sorts by value, balance, delegations in and delegations out.

### Issue link
[Find issue here](https://github.com/ecency/ecency-vision/issues/1040)

### Screenshot/video
[View on loom](https://www.loom.com/share/e724abd732cf4997825bb04680908709)

**Comment by feruzm** [comment]
@Adesojisouljay couple points: 

- Balance sorting should sort by most balance at top meaning desc, Value sorting should sort by getting getMetrics market value of token and show most valued at top meaning also desc.

image

- Delegations in working and delegation out not working.

**Comment by feruzm** [comment]
If new component, need test too. Simple props snapshot test.

**Comment by Adesojisouljay** [comment]
New branch created.

**Pull request closed without merging**
