### PR TITLE
Fix styling issue in Notifications

### PR DESCRIPTION
**Pull request by MTSaeed**
image

### CODE REVIEW

**Comment by feruzm** [comment]
@MTSaeed mobile browser looking good as well?

**Comment by MTSaeed** [comment]
https://user-images.githubusercontent.com/106739598/234827323-fca11d5a-1518-433b-a623-34c6e5e41b5e.mp4

**Comment by MTSaeed** [comment]
> @MTSaeed mobile browser looking good as well?

@feruzm Yes.

**Review by feruzm — APPROVED** [review]
lgtm

**Pull request merged**
