### PR TITLE
scss file for animations

### PR DESCRIPTION
**Pull request by igormuba**
Added a file specifically for animations, related to the issue
https://github.com/ecency/ecency-vision/issues/1149

### CODE REVIEW

**Comment by dkildar** [comment]
We have the `_animation.scss`. What the reason to creating of `_animations.scss`?

**Comment by igormuba** [comment]
> We have the `_animation.scss`. What the reason to creating of `_animations.scss`?

I was talking with @feruzm and we are thinking about adding animations that could or could not be used later. I am adding and testing a few animations (a few didn't work idk why) and will keep them in there in `_animations.scss`, separated from the `_animation.scss` that is in use

I am open to suggestions, thought, if someone has a different idea and wants to share.

**Comment by feruzm** [comment]
@igormuba we can combine those into single _animations.scss and use that going forward. I forgot about animation.scss when I commented. Idea is to keep all animations into single place organized.

**Comment by igormuba** [comment]
I updated and added some comments on how to use the new animations, left the originals but moved everything to _animations.scss

**Comment by dkildar** [comment]
lgtm

**Review by feruzm — APPROVED** [review]
lgtm, let's try out in action and see if animations improves ux

**Pull request merged**
