### PR TITLE
Fix tag selector bug

### PR DESCRIPTION
**Pull request by Adesojisouljay**
### What does this PR?
This PR fixes the bug on tags selector styling on submit page.

[Github issue](https://github.com/ecency/ecency-vision/issues/1411)

Screenshot
image

image

### CODE REVIEW

**Comment by feruzm** [comment]
@Adesojisouljay please check main search and make sure it doesn't break styling there. We use this component there too.

**Comment by Adesojisouljay** [comment]
Noted, will do that right away.

**Comment by Adesojisouljay** [comment]
> @Adesojisouljay please check main search and make sure it doesn't break styling there. We use this component there too.

I think its fine 
image

**Comment by feruzm** [comment]
@Adesojisouljay this component is used in many places, I checked couple places and it is broken there.

**Comment by Adesojisouljay** [comment]
> @Adesojisouljay this component is used in many places, I checked couple places and it is broken there.

Okay, please allow me do an overall/general
 check

**Comment by Adesojisouljay** [comment]
> @Adesojisouljay this component is used in many places, I checked couple places and it is broken there.

Did more checks on more components where it is used. I think its better right now

image

image

image

image

image

image

image

**Comment by Adesojisouljay** [comment]
> > @Adesojisouljay this component is used in many places, I checked couple places and it is broken there.
> 
> Did more checks on more components where it is used and some few adjustment made. I think its better right now
> 
> image
> 
> image
> 
> image
> 
> image
> 
> image
> 
> image
> 
> image

**Review by feruzm — APPROVED** [review]

**Pull request merged**
