### PR TITLE
Night theme photo zoom resolved

### LINKED ISSUE #1226: Bug: Night theme photo zoom mode
When in night theme, clicking on any image within posts, it zooms in image but sides seem white color.

### PR DESCRIPTION
**Pull request by MTSaeed**
**What does this PR?**

when entry images are zoom in, it Changes the background color of Entry Images according to the theme of the website. If theme is "Day" , it shows the background of entry images is "White". But when the theme is "Night" , it shows the background "Black".

**Steps to reproduce**

1. Open any Entry and click on the image of that entry. If your theme is "Day", it will show the background color to "White". But 
   if your theme is "Night", it will show the background color to "Black".

**Issue number** 

fixes #1226

**Screenshot / Video**

Bug: In Both "Day" and "Night" theme, the background of the entry images are white.

https://user-images.githubusercontent.com/106739598/224990371-d6d56aa5-613c-4980-8363-10ba5a0d359d.mp4

After Bug is Resolved: In "Day" theme the background of entry images is "white" while in "night" theme, the background of entry images is Black
 

https://user-images.githubusercontent.com/106739598/224990736-404d16a7-6870-4e03-8c5a-de6291f952c0.mp4

### CODE REVIEW

**Comment by MTSaeed** [comment]
image

**Review by feruzm — APPROVED** [review]
@MTSaeed LGTM, only component doesn't have test, could you add that before we merge?

**Comment by MTSaeed** [comment]
> @MTSaeed LGTM, only component doesn't have test, could you add that before we merge?

Sure. i will add it on Monday.

**Comment by MTSaeed** [comment]
image

**Comment by MTSaeed** [comment]
Hi @feruzm 
I have added the test for this component and this PR is also ready for merge.
Thanks!

**Review by feruzm — APPROVED** [review]
lgtm

**Pull request merged**
