### PR TITLE
fixed rc balances

### PR DESCRIPTION
**Pull request by Adesojisouljay**

### CODE REVIEW

**Comment by Adesojisouljay** [comment]
**What does this PR?**
When there is incoming Rc delegation, it should be reflected in used and available Rc balance.

**Comment by feruzm** [comment]
> **What does this PR?** When there is incoming Rc delegation, it should be reflected in used and available Rc balance.

Share screenshot please

**Comment by Adesojisouljay** [comment]
> 

Screenshot_20230319-104859_Discord

Here it says available 202M, used 1.01T but there is delegation in 4.36Q - 610B which means RC total is more in Quadrillion range, so used amount should be in that range.

**Review by feruzm — APPROVED** [review]
lgtm

**Pull request merged**
