### PR TITLE
Ecency wallet design update

### PR DESCRIPTION
**Pull request by talhasch**
Similar design as hive wallet

### CODE REVIEW

**Comment by talhasch** [comment]
@feruzm updated ecency wallet

**Comment by feruzm** [comment]
few minor changes in width of token type buttons and icon, Buy Points could be turned to button as well. 
We should be ok for release after these...

**Comment by feruzm** [comment]
@talhasch Great, only making Buy Points blue button and moving it slightly up, will be perfect.

image

**Comment by talhasch** [comment]
@feruzm done

**Review by feruzm — APPROVED** [review]
lgtm

**Pull request merged**
