### PR TITLE
Feat/sort communities in profile page

### PR DESCRIPTION
**Pull request by Adesojisouljay**

### CODE REVIEW

**Review by feruzm — CHANGES_REQUESTED** [review]
@Adesojisouljay I believe you misunderstood this feature. Idea wasn't to add sorting in Topics on home page but add sorting inside profile page communities page.
Not here:
Screenshot 2022-10-21 at 10 03 21


**But here:**


image

**Comment by Adesojisouljay** [comment]
Oh yes, I guess I misunderstood it, I will just move component to the right
place and restructure some few things.
Thanks

**Comment by feruzm** [comment]
@Adesojisouljay looking great, one small thing left. Since there is new component, please create props test.

**Review by feruzm — APPROVED** [review]
lgtm 👍

**Comment by Adesojisouljay** [comment]
🙏

**Pull request merged**
