### PR TITLE
Restyle code blocks

### PR DESCRIPTION
**Pull request by tipyy**

### CODE REVIEW

**Comment by tipyy** [comment]
This pull request restyles the code blocks.

Here is how it looks for day and night themes:

Screenshot 2021-10-10 at 13 21 10

Screenshot 2021-10-10 at 13 21 03

**Comment by tipyy** [comment]
Arf my bad, it includes the changes from another pull requests, but if the new style suits you, you can still cherry-pick the last commit

**Comment by feruzm** [comment]
@tipyy Looking great... Do you think HE PR is ready? I can do full review and merge, we can do few days of test on alpha.ecency.com

**Comment by tipyy** [comment]
Yep I think it can be merged.
There is still no actions (like stake/unstake tokens) but I use it on a daily basis

**Pull request merged**
