### PR TITLE
Animation after vote is cast

### LINKED ISSUE #1149: Animation after vote is cast
Right now, we have blinking animation while vote is processed/submitted, try to improve that after vote cast with animation.
We increase heart number so animation could be checked to do on heart icon or on vote icon. Best to see different variations and see if there can be structure for that animation to be configurable in future.

Something like this: 
https://lottiefiles.com/88955-reddit-up-vote
https://lottiefiles.com/96937-like-heart
https://lottiefiles.com/88219-upvote-splash-animation
https://lottiefiles.com/9729-upvote

### PR DESCRIPTION
**Pull request by MTSaeed**
**What does this PR?**
shows animation on vote button and heart icon.

**Steps to reproduce**

1. Give upVote or downVote to any post.
2. upVote has separate animation than downVote.

**Issue number** 

Fixes #1149

**Screenshot / Video**

https://user-images.githubusercontent.com/106739598/217539209-d7c92b50-e934-43b7-877d-e5ecce8a251c.mp4

### CODE REVIEW

**Comment by feruzm** [comment]
@MTSaeed Do you think, there is way to do this animation with svg file? https://lottiefiles.com/96937-like-heart

**Comment by feruzm** [comment]
@MTSaeed Check this video for tips: https://www.youtube.com/watch?v=i6QiDxujUgs

**Comment by MTSaeed** [comment]
> @MTSaeed Check this video for tips: https://www.youtube.com/watch?v=i6QiDxujUgs

I think, it would match your preference.

https://user-images.githubusercontent.com/106739598/217548520-d0742432-d866-4de3-af1e-1ef9748190a9.mp4

**Comment by feruzm** [comment]
> > @MTSaeed Check this video for tips: https://www.youtube.com/watch?v=i6QiDxujUgs
> 
> I think, it would match your preference.
> 
>  animation-changing.mp4

@MTSaeed Yes, it looks great. I am not sure about arrow animations though. Maybe we should keep them as it is for now.

**Comment by MTSaeed** [comment]
> 



> 

I basically used the styling of arrow animation for our Vote button. If its any post is upVoted, it will use rotate-scale-up animation. if post is downVoted, it will use the rotate-scale-down animation.

**Comment by feruzm** [comment]
> > 
> 
> Do you mean, not use any animation on Entry-vote-button after vote is cast? just used animation on Heart svg? I basically used the styling of arrow animation for our Vote button. If its any post is upVoted, it will use rotate-scale-up animation. if post is downVoted, it will use the rotate-scale-down animation.

Yes, arrow animation we can keep how it was, because 2 different style of animation next to each other looks too distractive and unnecessary. heart animation for now is enough and nice addition.

**Comment by MTSaeed** [comment]
> > > 
> > 
> > 
> > Do you mean, not use any animation on Entry-vote-button after vote is cast? just used animation on Heart svg? I basically used the styling of arrow animation for our Vote button. If its any post is upVoted, it will use rotate-scale-up animation. if post is downVoted, it will use the rotate-scale-down animation.
> 
> Yes, arrow animation we can keep how it was, because 2 different style of animation next to each other looks too distractive and unnecessary. heart animation for now is enough and nice addition.
@feruzm Updated.

**Review by feruzm — APPROVED** [review]
lgtm

**Pull request merged**
