### PR TITLE
Witnesses page

### PR DESCRIPTION
**Pull request by talhasch**

### CODE REVIEW

**Review by feruzm — COMMENTED** [review]
Looking good, only in desktop view, I would prefer bit smaller screen width.
Right now, it is from edge of one side to other edge of another side. Perhaps make it smaller on desktop view same size as post content area size, other sides can stay white space.

image

**Comment by talhasch** [comment]
@feruzm we can limit size for large screen for both web and desktop?

**Comment by feruzm** [comment]
@talhasch yes, some padding on desktop wouldn't hurt as well. Default screen size for desktop app is smaller than browser default size, at least for some users, desktop could have less padding compare to browser, imo.

**Comment by talhasch** [comment]
ok. have set max-width: 1200px. looking good for both web and desktop.

**Review by feruzm — APPROVED** [review]
lgtm

**Pull request merged**
