### PR TITLE
Post after 7 days

### PR DESCRIPTION
**Pull request by MTSaeed**
**fixes** #776 

https://github.com/ecency/ecency-vision/pull/1176 

https://user-images.githubusercontent.com/106739598/230361990-b5d62733-38e4-4924-a35d-c7a4af3673ee.mp4

### CODE REVIEW

**Comment by MTSaeed** [comment]
image

**Comment by dkildar** [comment]
LGTM

**Comment by MTSaeed** [comment]
> @MTSaeed Tipping dialog should show Points as well. Of course, make sure `export USE_PRIVATE="1"` env is set before doing `yarn start`.

Yeah. it is also working for points.
image

**Review by feruzm — APPROVED** [review]
lgtm

**Pull request merged**
