### PR TITLE
Detailed hive engine wallet

### PR DESCRIPTION
**Pull request by shawnpringle**
IN this fork the user is given more control over the hive engine tokens.  You will be able to delegate, remove delegations.  You will also get a detailed transaction list of Hive engine transactions when you choose a particular hive engine token .

### CODE REVIEW

**Comment by shawnpringle** [comment]
i have a few failing tests that I don't understand yet.  Take a look at the proofofbrain.blog site to see how clicking on the various HE token names open up and also http://localhost/hive-150329/@leprechaun/proof-of-brain-changes

**Comment by feruzm** [comment]
@shawnpringle this looks like great improvement, probably need extensive review. @Adesojisouljay Could you please do initial review of these changes?

**Comment by Adesojisouljay** [comment]
@shawnpringle, This feature looks so great, could you please make the following changes ?

- Format token balances properly, remove all comas after decimal
- Check history modal, load more button is not visible for some tokens with more history, also check scroll behavior
- You can make entire card clickable and give cursor a className of pointer to make users know it's clickable, instead of setting that light color for token symbol
- I'm not sure there is a need for dropdown in actions modal, when user clicks a token, actions(transfer, stake, unstake, delegate, etc) should be performed on that token. If we are adding dropdown, could you please let dropdown be consistent with history dropdown ? That should look more nicer

You can work on those changes for now and let's see how it'll look

**Comment by shawnpringle** [comment]
It is after the decimal point where we need commas more often.  Honestly
figuring out whether a number is 155 millionths or 155 hundred thousandths
of a Bitcoin is far far easier when commas are consistently applied
throughout the number.  I want to keep them.  Being an open source project
and license, you can always run with making further changes according to
the team's tastes.

**Comment by Adesojisouljay** [comment]
>@shawnpringle Please check those comas and format, for example; 

- 180.007777999 is showing as 180.007,777,999, 
- 0.7777777 shows as 0.777,777,7 

You should either round to few decimal places or remove comas we can show as 180.01 and 0.78 or display balance without rounding( the way we currently have it)

**Comment by shawnpringle** [comment]
I agree there shouldn't be a trailing comma.  A number like
180.007,777,999, formatted to 8 fraction digits will be changed to
180.007,778,00 unless you set the truncate flag in the options.  In this
case the number would be 180.007,777,99.  Displaying numbers like this when
there are repeating digits are a lot clearer to the reader.  How long does
it take you to read 0.000001?  How long does it take you to read
0.000,001?  Using BTC mode for displaying rewards needs more fraction
digits than two.

**Comment by feruzm** [comment]
This is great effort, @shawnpringle please check this issue which has some ideas about our vision for wallet page, evolution of it and in effort to unify experience with mobile app, we are going to move more this direction.

https://github.com/ecency/ecency-vision/issues/1172

Your implementation is quite similar to that and modal popup could be done as separate page and a lot of minor tweaks. This in itself is huge change and improvement, please create branch within this repo (you already have permission), so we can develop it together.

**Comment by shawnpringle** [comment]
That's a great idea.

**Comment by shawnpringle** [comment]
Git has always made me feel like an elephant trying to ride a bicycle.
Whenever I want to do something more advanced than pushing or pulling it I
feel like I am going to squash and break something.  It doesn't look like I
have permission to make branches on your repo.  Of course to me it is
probably because elephants don't ride bicycles.  So, I named your repo
upstream and the one I use I have called github instead of 'origin'.  And
the dialog with the shell looks like this:
Crowne:~/Source/ecency-vision$ git push github
feature/engine-wallet-detail-as-another-page
Total 0 (delta 0), reused 0 (delta 0)
remote:
remote: Create a pull request for
'feature/engine-wallet-detail-as-another-page' on GitHub by visiting:
remote:
https://github.com/steemfiles/ecency-vision/pull/new/feature/engine-wallet-detail-as-another-page
remote:
To ssh://github.com/steemfiles/ecency-vision
 * [new branch]          feature/engine-wallet-detail-as-another-page ->
feature/engine-wallet-detail-as-another-page
***@***.***:~/Source/ecency-vision$ git push upstream
 feature/engine-wallet-detail-as-another-page
ERROR: Permission to ecency/ecency-vision.git denied to shawnpringle.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.


Also the upstream entry in the .git/config is ssh and not https as I
thought might have been the problem:
[remote "upstream"]
url = ***@***.***/ecency/ecency-vision
fetch = +refs/heads/*:refs/remotes/upstream/*

So I created feature/engine-wallet-detail-as-another-page and it is
consistent with your conventions on the one in my fork.  Can you pull that
in?

**Comment by feruzm** [comment]
@shawnpringle I apologize, looks like in one of our clean ups, someone removed your username, weird. I added back.

You should be able to this directly now:

```
git checkout -b new-branch-xyz
//make your changes
git commit -am 'this is new feature commit message'
git push origin new-branch-xyz
```

**Comment by feruzm** [comment]
Closing in favor of #1183, we will be adding features into that PR. Thank you! @Adesojisouljay please collaborate with @shawnpringle and check his work on this branch so it will save you some time to implementing detail pages.

**Comment by Adesojisouljay** [comment]
> Closing in favor of #1183, we will be adding features into that PR. Thank you! @Adesojisouljay please collaborate with @shawnpringle and check his work on this branch so it will save you some time to implementing detail pages.

Thanks, noted
I'll do that

**Pull request closed without merging**
