### PR TITLE
Password update

### PR DESCRIPTION
**Pull request by talhasch**

### CODE REVIEW

**Comment by talhasch** [comment]
@feruzm ?

**Review by feruzm — APPROVED** [review]
Looks good, only this gives me thought on how to show/fix hivesigner that it detects if account has changed password that is saved in localstorage

**Comment by talhasch** [comment]
> Looks good, only this gives me thought on how to show/fix hivesigner that it detects if account has changed password that is saved in localstorage

Comparing public keys may be a solution. Hivesigner creates public keys from password that stored in local storage and compares with one of the actual public keys. Does it makes sense?

**Comment by talhasch** [comment]
@feruzm do we need to refresh token after password update?

**Comment by feruzm** [comment]
Yea that’s what I thought of doing as well until our reimplementation will be ready.

Access token should continue to work as long as posting authority is not removed in process. We might need to update active key in redux if it is kept.

**Pull request merged**
