### PR TITLE
Submit page validation improvements

### PR DESCRIPTION
**Pull request by talhasch**

### CODE REVIEW

**Comment by feruzm** [comment]
@talhasch Nice, could we also add Tag-selector component line 66: `if (e.keyCode === 13) {` add this `|| e.keyCode === 32 || e.keyCode === 188` into tag selector for space and comma ? Much easier to follow for some people..

**Comment by talhasch** [comment]
@feruzm sure

**Comment by talhasch** [comment]
done

**Review by feruzm — APPROVED** [review]
lgtm

**Pull request merged**
