### PR TITLE
hot topics

### PR DESCRIPTION
**Pull request by talhasch**
Adds hot topics section above trending tags list which we create a list out of a defined tag list.

### CODE REVIEW

**Comment by talhasch** [comment]
@feruzm i am open for color suggestions

**Comment by feruzm** [comment]
@talhasch let's keep icon same color as font, just like in dark mode, they don't have to be too much attention attracting.

**Comment by feruzm** [comment]
Please add `Gaming` section with `hive-140217` as well.

**Comment by talhasch** [comment]
done

**Review by feruzm — APPROVED** [review]
lgtm 🚀

**Pull request merged**
