### PR TITLE
Update packages

### PR DESCRIPTION
**Pull request by dkildar**

### CODE REVIEW

**Comment by feruzm** [comment]
@dkildar Debugger/compiler complaining about few deprecation I think related to typescript version update:

```
DeprecationWarning: 'updateSourceFile' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.
DeprecationWarning: 'createStringLiteral' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.
DeprecationWarning: 'createReturnStatement' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.
DeprecationWarning: 'createBlock' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.
DeprecationWarning: 'createMethodDeclaration' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.
DeprecationWarning: 'createIdentifier' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.
DeprecationWarning: 'createCallExpression' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.
DeprecationWarning: 'createParameterDeclaration' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.
DeprecationWarning: 'createPropertyAssignment' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation con
```

**Comment by dkildar** [comment]
@feruzm We can't fix it right now because need to update web pack. It should be separated branch

**Comment by feruzm** [comment]
> @feruzm We can't fix it right now because need to update web pack. It should be separated branch

@dkildar looks like there is issues with tests, check `yarn test`

**Comment by dkildar** [comment]
@feruzm take a look please

**Comment by feruzm** [comment]
@dkildar Few tests still causing issues.

**Review by feruzm — APPROVED** [review]
lgtm, we still need to check webpack issues in separate PR @dkildar

**Pull request merged**
