### PR TITLE
Am/gifs functionality

### PR DESCRIPTION
**Pull request by ArmishMunir**
gifs functionality being added, using GIPHY api.

### CODE REVIEW

**Comment by feruzm** [comment]
@Adesojisouljay Looks like we need to add `Powered by GIPHY` in Gif search dropdown at the bottom right side. This attribution is required by giphy since we using their api.

**Review by feruzm — APPROVED** [review]
lgtm, only credit info should be added.

**Comment by Adesojisouljay** [comment]
> @Adesojisouljay Looks like we need to add `Powered by GIPHY` in Gif search dropdown at the bottom right side. This attribution is required by giphy since we using their api.

That's true, will add that.

**Review by feruzm — APPROVED** [review]
Lgtm

**Pull request merged**
